#!/bin/bash

echoerr() { printf "%s\n" "$*" >&2; }

if [ "$AWS_ACCESS_KEY_ID" == "" ] ; then
    echoerr "environment variable AWS_ACCESS_KEY_ID must be defined" 
    exit 1
fi
if [ "$AWS_SECRET_ACCESS_KEY" == "" ] ; then
    echoerr "environment variable AWS_SECRET_ACCESS_KEY must be defined"
    exit 1
fi
if [ "$AWS_DEFAULT_REGION" == "" ] ; then
    echoerr "environment variable AWS_DEFAULT_REGION must be defined"
    exit 1
fi
if [ "$AWS_REGION" == "" ] ; then
    echoerr "environment variable AWS_REGION must be defined"
    exit 1
fi

