#! /bin/bash
E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )
#define the function
find_newest_file_matching_pattern_under_directory(){
    echo $(find $1 -maxdepth 1 -name "$2" -print0 | xargs -0 ls -1 -t | head -1)
}

marc4j_jar=$( find_newest_file_matching_pattern_under_directory $scriptdir "marc4j*.jar" )

if [ $# -eq 0 ]
then
    echo "    Usage: `basename $0` ./path/to/marc.mrc ./path/to/marc.mrc " 1>&2
    exit $E_BADARGS
fi

#echo "java -jar $marc4j_jar marcupdate $* " 1>&2

java -jar $marc4j_jar marcupdate $*

exit 0

