#!/bin/bash

SCRIPTDIR=$( (cd -P $(dirname ${BASH_SOURCE[0]:-$(/bin/pwd)/dummy}) && /bin/pwd) )
COREDIR=$( dirname $SCRIPTDIR  )
corename=hathi
DATADIR=$SCRIPTDIR/data

# load the shared bash functions log, vlog and Verbose
. $SCRIPTDIR/outputfuncs.bash $SCRIPTDIR


verbose=
force=
test=
index=staging:production
while getopts :vti: opt
 do
      case $opt in
          v) verbose=-v;;
          i) index=$OPTARG;;
          t) test=-t;;
      esac
done
shift $((OPTIND-1))

for line in `cat $SCRIPTDIR/cores_to_process`
do 
    year=`date "+%Y"`
    solrname=`echo $line| cut -d '|' -f1`
    add_bucket=`echo $line| cut -d '|' -f2 | sed -e "s/YYYY/$year/"`
    del_bucket=`echo $line| cut -d '|' -f3 | sed -e "s/YYYY/$year/"`

    if [[ "$index" =~ $solrname ]]; then
        Verbose "Indexing all records into core $solrname"
        # process files into specified index

        FULLDUMPDIR=$DATADIR/full_dump

        for file in `find $FULLDUMPDIR -name "*.mrc"`
        do
            Verbose "Sending full dump portion $file to $corename core"
            if [[ "$test" != "-t" ]] ; then
                aws s3 cp $file $add_bucket 2>&1 | vlog "      "
            else
                Verbose "aws s3 cp $file $add_bucket "
            fi
        done
    else 
        Verbose "Skipping indexing all records into core $solrname"
    fi
done

